require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  DisplayStyleGuide: true
  Include:
    - '**/*.rb'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#']
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 7
