language: ruby
rvm:
  - 2.6.3
cache:
  - bundler
services:
  - postgresql
env:
  matrix:
    - DISABLE_SPRING=true
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup RAILS_ENV=test
script:
  - bundle exec rubocop
  - bundle exec rails test
  - bundle exec bundle-audit check --update
  - bundle exec brakeman
branches:
  only:
    - dev
    - master
