language: ruby
rvm:
- 2.6.3
branches:
  only:
    - master

cache:
  bundler: true
  npm: true
  yarn: true
  directories:
    - node_modules

before_install:
  - gem update --system
  - gem install bundler --no-document

install:
  - npm i -g yarn
  - bundle install
  - yarn install

stages:
  - name: lint
  - name: test
#  - name: deploy

before_script:
  - gem install brakeman
  - bundle exec rake db:setup
  - bundle exec rake assets:precompile

jobs:
  include:
    - stage: lint        
      script:
        - bundle exec rubocop
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - brakeman -z
    - stage: test
      script:
        - bundle exec test
    # - stage: deploy
    #   script: skip
    #   deploy:
    #     provider: heroku
    #     api_key:
    #       secure: ""
    #     on:
    #       branch: master
    #     run: rails db:migrate
