language: ruby
rvm:
- 2.6.2
branches:
  only:
    - master

cache:
  bundler: true
  npm: true
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - source /home/travis/.bashrc

install:
  - bundle install
  - yarn install

stages:
  - name: lint
  - name: test
  - name: deploy

jobs:
  include:
    - stage: lint
      script:
        - bundle exec rubocop
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - bundle exec test
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: ""
        on:
          branch: master
        run: rails db:migrate
