version: '3'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/ejemplo-configuracion
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    links:
      - postgres
volumes:
  postgres:
  bundler_gems:
